package Controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;
import java.sql.SQLException;

import application.Main;
import Database.MySQLDatabase;
import javafx.event.ActionEvent;

import javafx.scene.layout.BorderPane;

public class CashierScreenController {
	@FXML
	private BorderPane welcomeBorder;
	@FXML
	private Button ProcessSale;
	@FXML
	private Button logout;

	// Event Listener on Button[#ProcessSale].onAction
	@FXML
	public void ProcessSaleScreen(ActionEvent event) throws SQLException, Exception {
		PaymentController.tot="";PaymentController.np="";PaymentController.rt=null;
		System.out.println("Authenticate");
		ProcessSaleController.SaleNo++;
		MySQLDatabase.getInstance().addSale();
		Parent root = FXMLLoader.load(getClass().getResource("/GUI/ProcessSale.fxml"));

		Scene scene = new Scene(root, 1920, 990);
		Main.Get_Stage().setScene(scene);
		Main.Get_Stage().setTitle("Process Sale");
		Main.Get_Stage().show();
		//Main.changeRoot(root);
		//Main.screenSizeSet(1900, 990);

	}
	// Event Listener on Button[#logout].onAction
	@FXML
	public void Back(ActionEvent event) throws IOException {
		Parent root = FXMLLoader.load(getClass().getResource("/GUI/Login.fxml"));
		Scene scene = new Scene(root, 1920, 990);
		Main.Get_Stage().setScene(scene);
		Main.Get_Stage().show();
		//Main.changeRoot(root);
		//Main.screenSizeSet(1900, 990);
		// TODO Autogenerated
	}
}
