package Controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;

import application.Main;
import javafx.event.ActionEvent;

import javafx.scene.layout.BorderPane;

public class CustomerScreenController {
	@FXML
	private BorderPane welcomeBorder;
	@FXML
	private Button searchRobot;
	@FXML
	private Button customDemand;

	// Event Listener on Button[#ProcessSale].onAction
	@FXML
	public void searchRobotScreen(ActionEvent event) throws IOException {
		Parent root = FXMLLoader.load(getClass().getResource("/GUI/SearchErobot.fxml"));
		Scene scene = new Scene(root, 1920, 990);
		Main.Get_Stage().setScene(scene);
		Main.Get_Stage().setTitle("Search E_Robot");
		Main.Get_Stage().show();
	}

	@FXML
	public void customDemandScreen(ActionEvent event) throws IOException {
		Parent root = FXMLLoader.load(getClass().getResource("/GUI/CustomDemand.fxml"));
		Scene scene = new Scene(root, 1920, 990);
		Main.Get_Stage().setScene(scene);
		Main.Get_Stage().show();
		// TODO Autogenerated
	}


	// Event Listener on Button[#logout].onAction
	@FXML
	public void back(ActionEvent event) throws IOException {
		Parent root = FXMLLoader.load(getClass().getResource("/GUI/Login.fxml"));
		Scene scene = new Scene(root, 1920, 990);
		Main.Get_Stage().setScene(scene);
		Main.Get_Stage().show();
		// TODO Autogenerated
	}
}
